Manage your plan update
workstaffhq/helpcenter pull request #42
Opened 2024-10-09 13:32 UTC by phisog

2024-10-17 16:24 UTC, davidmarquis requested changes

2024-10-17 16:24 UTC, davidmarquis commented on docs/managers/billing/manage-plan.md
> +You can take advantage of a free 14-day trial of the Max plan that you can start yourself directly within Workstaff.
La seule manière de démarrer un trial maintenant est de contacter un sales

2024-10-17 16:24 UTC, davidmarquis commented on docs/managers/billing/manage-plan.md
> +When you first sign up on Workstaff, your account is on the **Max plan** by default, our most advanced offering, for up to 5 workers.
À revoir ou retirer puisque nous ne mettons plus du tout l'emphase sur le trial dans le processus de vente/conversion

2024-10-21 18:42 UTC, phisog commented on docs/managers/billing/manage-plan.md
> +When you first sign up on Workstaff, your account is on the **Max plan** by default, our most advanced offering, for up to 5 workers.
merci pour l'info ! j'ai retiré complètement en mettant le lien vers "Book a demo"

2024-10-21 19:52 UTC, davidmarquis approved these changes

2024-10-21 19:52 UTC, merged